### ISSUE TITLE
Consider consolidating with or bundling Storybook

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli-utils-docsite#59]
Our UI library (https://ui.dhis2.nu) uses Storybook for component demos.  @ismay and others have mentioned concerns about bifurcating our documentation tooling, especially when it comes to documenting component usage and API interfaces.  We should consider either - (1) moving all our documentation into Storybook or (2) bundling Storybook support into the docsite tool, as first-class for component demos, and work to auto-generate props lists in either Storybook or Docsify.

**Comment by amcgee** [comment]
@HendrikThePendric shared a few examples using Storybook as the top-level doc tool:

https://storybook.js.org/docs/examples/
https://wix-style-react.now.sh/

**Comment by varl** [comment]
Superseded by https://jira.dhis2.org/browse/CLI-4.
